### ISSUE TITLE
"Use current location" is unresponsive when used as the start location when getting directions

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#154] opened 2020-04-01 03:28 UTC
**Steps to reproduce:**
1. Tap the navigation button found at the bottom left
2. Enter a destination location with any of the functioning options
3. Make sure locations is turned on and the app has locations permissions
4. Tap on "Use current location"

**Expected:**
- Current location should be used and the following screen should be the navigation route/directions

**Actual:**
- Nothing happens after tapping on "Use current location" in step 4 of Directions

**Comment by sharon-ho** [comment] 2020-04-12 00:41
Need someone to test this on their mobile devices because it works for some team members and doesn't for others.

**Comment by felixlapierre** [comment] 2020-04-19 01:48
Closing this as cannot reproduce since i constantly use this feature and it works fine on my end.

**Closed as completed by felixlapierre** 2020-04-19 01:48 UTC
Labels: bug
