### ISSUE TITLE
Center location button is unresponsive

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#151] opened 2020-04-01 02:25 UTC
**Steps to reproduce:**
 1. Tap on the center location button found at the bottom right
 2. No pop-up appears after giving permissions the first time as detailed here: #96
 3. Nothing happens when tapped even with locations turned on

**Expected:**
- A marker should indicate the user's current location or the user's location should be marked with a blue dot (optional, #74)

**Actual:**
- There is no response or action done after clicking the center location button found at the bottom right

**Comment by MikeBrichko** [comment] 2020-04-09 13:40
I tested it on my phone and it works for me. It does not work on Anissa's and Sharon's phone. I will put this bug under review and ask the reviewer to test it on their phone as well.

**Comment by felixlapierre** [comment] 2020-04-19 01:41
Closing this as I am unable to reproduce on the latest version of the app. I'll reopen if someone can repro and give me a screenshot of an error message.

**Closed as completed by felixlapierre** 2020-04-19 01:41 UTC
Labels: bug
