### ISSUE TITLE
Application hangs when parsing directions response

### ISSUE THREAD

**Issue by felixlapierre** [felixlapierre/campus-guide#54] opened 2020-02-25 21:36 UTC
**Steps to reproduce:**
- Click on the "Navigate" button in the bottom left
- Enter a start and end location
- Click "OK"

**Observed:**
- For a few seconds the app will not respond: clicking on buttons and dragging the map will do nothing

**Expected:**
- The app continues to respond while the directions are loaded

**Likely cause:**
- The parsing of the JSON response from the server is done on the UI thread, preventing any UI rendering from being done during the parsing (which can take a while since the response is a rather large JSON object

**Comment by jonZlotnik** [comment] 2020-03-11 04:10
I actually don't think this is the case... It works fine for me.
I mean, there's no loading symbol to let the user know that the directions are loading, but the app definitely doesn't freeze.

**Comment by jonZlotnik** [comment] 2020-03-11 04:12
It seems your co-routine is working as expected

**Comment by jonZlotnik** [comment] 2020-03-24 15:22
Can't reproduce issue. Seems to be fixed now.

**Closed as completed by jonZlotnik** 2020-03-24 15:22 UTC
Labels: bug
